### PR TITLE
Feature/183/alert component

### LINKED ISSUE #183: Make it clearer that this is the new official site, with a clearer link to the old one
### Describe the problem

As talked about in #179 it was unclear to me (and others) that there is a new version of the site and that you can find the old one on another subdomain. Currently there is a paragraph that kind of explains this with a link to the old version. But this is in my opinion very easily missed. And seeing as this site does not yet have all the information of the old one, I think it would benefit everyone if this was made more clear.

### Describe the proposed solution

I am not an UX designer, but I think a banner in the header of every page would be the most clear. Maybe in yellow so that it looks like a warning. Something along the lines of: "You're browsing the new improved version of the website, not everything is already here so click here to go to the old version."

Maybe retain the banner for a while even when all information is here, just so that people know this is the new official one.

### Alternatives considered

_No response_

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by NoWarries**
# Description

Closes #183 

Added a concept Alert component for usage in for example the issue described in #183 

Screenshot 2023-10-20 at 15-25-25 ICT Research Methods — Methods Pack for Research in ICT

Has several configuration options, easily scalable

Screenshot 2023-10-20 at 14-40-47 ICT Research Methods — Methods Pack for Research in ICT

Works alright on darkmode. Readable

Screenshot 2023-10-20 at 15-35-52 ICT Research Methods — Methods Pack for Research in ICT

## Type of change

Please select the option that is relevant

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] All the required documentation is added.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

# Additional information

### Placement
Not sure if this is the right place to put the alert box. Should it be added to more pages? ~~Do we still need a sidenav item to resolve #183~~ #184

Do we even need this with the sidenav implemented?

### Icons
I am not sure what icons are used (which libary). Thus I cannot add icons appropiate for the Alert. e.g. a checkmark on a success message. All use information icon for now

### CODE REVIEW

**Comment by jochemvogel** [comment]
Thanks. Personally I don't agree with the prominent place the alert gets. I did it more subtle here (https://deploy-preview-184--stellular-banoffee-031bf4.netlify.app/)

I do think we can use this alert boxes on other routes:

1. https://ictresearchmethods.nl/research-pattern-navigator/
2. https://ictresearchmethods.nl/methods-overview/

Going to create a new version of the methods overview next week, so an alert, that the content might be more clear on the old site, might work for now.

Could you implement the info/blue one on top of those two pages. That will definitely help the user.

Thanks!

**Comment by NoWarries** [comment]
> Thanks. Personally I don't agree with the prominent place the alert gets. I did it more subtle here (https://deploy-preview-184--stellular-banoffee-031bf4.netlify.app/)
> 
> I do think we can use this alert boxes on other routes:
> 
>     1. https://ictresearchmethods.nl/research-pattern-navigator/
> 
>     2. https://ictresearchmethods.nl/methods-overview/
> 
> 
> Going to create a new version of the methods overview next week, so an alert, that the content might be more clear on the old site, might work for now.
> 
> Could you implement the info/blue one on top of those two pages. That will definitely help the user.
> 
> Thanks!

Honestly agree.

Will revert changes on the homepage so the component is isolated in the branch.
Otherwise feel free to cherypick if deemed component could be useful

**Comment by jochemvogel** [comment]
Perfect! I've merged the other one. The additions on this MR might be very helpful for the users that prefer the old one.

Not planning to keep the wiki all the time, but collecting feedback from the users is very helpful to eventually remove the whole wiki.

**Comment by jochemvogel** [comment]
@NoWarries I was wrong. It's pretty nice to have those alert boxes on the main page. I added those and will merge it. You can adjust things if you want, but it's comparable with your initial design.

**Pull request merged**
