### PR TITLE
Feature/color coded method cards

### PR DESCRIPTION
**Pull request by NoWarries**
# Description
While browsing the website, I noticed that it can be challenging to differentiate between the various categories. I decided to quickly write something up for this. And although this implementation certainly isn't my best work. I think it is a good starting point for the ongoing color discussion #171 

MethodCards now have category-based colors making it easier for users to distinguish and organize the methods. Enhancing visual clarity and simplifying navigation. To avoid visual conflicts with these colors, the former purple tags adapt with these colors. The method tabs color also match the category color for a harmonized color scheme.

## Examples
Screenshot 2023-10-11 at 20-26-56 ICT Research Methods — Methods Pack for Research in ICT
Screenshot 2023-10-11 at 20-26-44 ICT Research Methods — Methods Pack for Research in ICT

## Type of change

Please select the option that is relevant

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] All the required documentation is added.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

# Additional information

### WCAG SC 1.4.3
The current implementation utilizes color codes that closely resemble those used in the card sets. However, this design choice has resulted in some text elements, particularly in the showroom, being challenging to read. We should consider using more legible alternatives. 

Screenshot 2023-10-11 at 20-36-27 Methods - ICT research methods
Reference: colors used in the table on https://oud.ictresearchmethods.nl/Methods

### Primary
It appears that the primary color used in the application clashes with the theming based on method categories. The purple hue is quite reminiscent of lab colors, which can create a conflicting visual experience.

### CODE REVIEW

**Comment by jochemvogel** [comment]
Hi @NoWarries, thank you! Very nice addition, like it. Could you also add it to the buttons on the Patterns page? 
image

I'll have a look at the primary color on dark mode. I agree it's conflicting with the Lab color. Thanks!

**Comment by NoWarries** [comment]
@jochemvogel added color theming for tags on pattern navigator page
Screenshot 2023-10-16 at 15-34-43 ICT Research Methods — Methods Pack for Research in ICT

**Comment by NoWarries** [comment]
Q1: Why doesn't the pattern navigator page use the existing tag component? Should/can we consider this?

Q2: Currently, the tag component has a white border (this is because the border color has now been replaced with a background with white text). What is desirable?

**Comment by NoWarries** [comment]
> Q1: Why doesn't the pattern navigator page use the existing tag component? Should/can we consider this?
> 
> Q2: Currently, the tag component has a white border (this is because the border color has now been replaced with a background with white text). What is desirable?

I suggest the following: https://github.com/HBO-i/ictresearchmethods.nl/pull/177/commits/4e567ba2d1ace6917f04c2e8acb01b806095d4a0

**Comment by jochemvogel** [comment]
> Q1: Why doesn't the pattern navigator page use the existing tag component? Should/can we consider this?
> 
> Q2: Currently, the tag component has a white border (this is because the border color has now been replaced with a background with white text). What is desirable?

Q1: Was easy to re-use. No idea behind it.

Q2: Current design is good. I like to removed border, thanks.

**Pull request merged**
